-- =====================================================
-- 金宇轮胎APS系统 - 成型排程数据库建表脚本
-- 版本：V2.0.0
-- 数据库：MySQL 8.0+
-- =====================================================

-- 设置字符集
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- =====================================================
-- 1. 主数据表 (MDM - Master Data Management)
-- =====================================================

-- ---------------------------------------------------
-- 1.1 成型机台信息表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_MOLDING_MACHINE`;
CREATE TABLE `T_MDM_MOLDING_MACHINE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `CX_MACHINE_CODE` VARCHAR(50) NOT NULL COMMENT '成型机编码',
    `CX_MACHINE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '成型机名称',
    `CX_MACHINE_TYPE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '成型机类型编码',
    `CX_MACHINE_TYPE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '成型机类型名称',
    `CX_MACHINE_MODEL` VARCHAR(100) DEFAULT NULL COMMENT '机型型号',
    `WRAPPING_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '反包方式',
    `HAS_ZERO_DEGREE_FEEDER` INT DEFAULT 0 COMMENT '是否有零度供料架：0-否 1-是',
    `CURRENT_STRUCTURE` VARCHAR(100) DEFAULT NULL COMMENT '当前在产结构',
    `PRODUCTION_CAPACITY` DECIMAL(10,2) DEFAULT NULL COMMENT '每小时产能（条）',
    `MAX_DAILY_CAPACITY` INT DEFAULT NULL COMMENT '设备最大日产能（条）',
    `MAX_CURING_MACHINES` INT DEFAULT NULL COMMENT '对应硫化机上限数量',
    `LINE_NUMBER` INT DEFAULT NULL COMMENT '产线编号',
    `MAINTAIN_STATUS` VARCHAR(10) DEFAULT '0' COMMENT '机台状态：0-正常 1-维护中 2-故障 3-停用',
    `MAINTAIN_START_TIME` DATETIME DEFAULT NULL COMMENT '维护开始时间',
    `MAINTAIN_END_TIME` DATETIME DEFAULT NULL COMMENT '维护结束时间',
    `PRODUCTION_RESTRICTION` VARCHAR(500) DEFAULT NULL COMMENT '排产限制说明',
    `IS_ACTIVE` INT DEFAULT 1 COMMENT '是否启用：0-禁用 1-启用',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_MACHINE_CODE` (`CX_MACHINE_CODE`),
    KEY `IDX_FACTORY_CODE` (`FACTORY_CODE`),
    KEY `IDX_MACHINE_TYPE` (`CX_MACHINE_TYPE_CODE`),
    KEY `IDX_MAINTAIN_STATUS` (`MAINTAIN_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型机台信息表';

-- ---------------------------------------------------
-- 1.2 物料信息表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_MATERIAL_INFO`;
CREATE TABLE `T_MDM_MATERIAL_INFO` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `MES_MATERIAL_CATEGORY` VARCHAR(50) DEFAULT NULL COMMENT 'MES物料大类编码',
    `MES_MATERIAL_SUBCATEGORY` VARCHAR(50) DEFAULT NULL COMMENT 'MES物料细类编码',
    `MES_MATERIAL_CATE_NAME` VARCHAR(100) DEFAULT NULL COMMENT 'MES物料大类名称',
    `MES_MATERIAL_SUBCAT_NAME` VARCHAR(100) DEFAULT NULL COMMENT 'MES物料细类名称',
    `MATERIAL_CATEGORY` VARCHAR(50) DEFAULT NULL COMMENT '物料类型',
    `PRODUCT_CATEGORY` VARCHAR(50) DEFAULT NULL COMMENT '产品分类',
    `STRUCTURE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '结构',
    `MATERIAL_CODE` VARCHAR(50) NOT NULL COMMENT '物料编号',
    `MES_MATERIAL_CODE` VARCHAR(50) DEFAULT NULL COMMENT 'MES物料编号',
    `MATERIAL_DESC` VARCHAR(200) DEFAULT NULL COMMENT '物料描述',
    `SPECIFICATIONS` VARCHAR(100) DEFAULT NULL COMMENT '规格',
    `MAIN_PATTERN` VARCHAR(100) DEFAULT NULL COMMENT '主花纹',
    `PATTERN` VARCHAR(100) DEFAULT NULL COMMENT '花纹',
    `BRAND` VARCHAR(50) DEFAULT NULL COMMENT '品牌',
    `SPEED` VARCHAR(50) DEFAULT NULL COMMENT '速度',
    `HIERARCHY` VARCHAR(50) DEFAULT NULL COMMENT '层级',
    `PRO_SIZE` VARCHAR(50) DEFAULT NULL COMMENT '英寸',
    `ABILITY` VARCHAR(50) DEFAULT NULL COMMENT '性能',
    `CANT_PRODUCE` INT DEFAULT 0 COMMENT '不可生产：0-否 1-是',
    `EMBRYO_CODE` VARCHAR(50) DEFAULT NULL COMMENT '胎胚编码',
    `EMBRYO_DESC` VARCHAR(200) DEFAULT NULL COMMENT '胎胚描述',
    `SECTION_WIDTH` VARCHAR(50) DEFAULT NULL COMMENT '断面宽',
    `PRODUCT_TYPE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '品名编码',
    `PRODUCT_TYPE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '品名',
    `MOULD_CATEGORY` VARCHAR(50) DEFAULT NULL COMMENT '模具大类',
    `TIRE_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '轮胎类型',
    `COMMON_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '公用类型',
    `REPLACE_GROUP` VARCHAR(50) DEFAULT NULL COMMENT '替换品种分组',
    `NO_DELIVERY` INT DEFAULT 0 COMMENT '不能发货：0-否 1-是',
    `ENVIRONMENT_PROTECTION` VARCHAR(100) DEFAULT NULL COMMENT '环保',
    `AUTHENTICATION` VARCHAR(200) DEFAULT NULL COMMENT '认证串',
    `MATERIAL_GROUP_CODE` VARCHAR(50) DEFAULT NULL COMMENT '物料组',
    `FORBID_TAG` VARCHAR(10) DEFAULT NULL COMMENT '废停标志',
    `SINGLE_TIRE_WEIGHT` DECIMAL(10,4) DEFAULT NULL COMMENT '单胎重量',
    `MOULD_CLAMPING_PRESSURE` DECIMAL(10,2) DEFAULT NULL COMMENT '合模压力PA',
    `GROSS_RATE_JSON` TEXT DEFAULT NULL COMMENT '毛利率Json',
    `QUALITY_STATE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '质控状态',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_MATERIAL_CODE` (`FACTORY_CODE`, `MATERIAL_CODE`),
    KEY `IDX_STRUCTURE_NAME` (`STRUCTURE_NAME`),
    KEY `IDX_EMBRYO_CODE` (`EMBRYO_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='物料信息表';

-- ---------------------------------------------------
-- 1.3 成型固定机台表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_CX_MACHINE_FIXED`;
CREATE TABLE `T_MDM_CX_MACHINE_FIXED` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `CX_MACHINE_CODE` VARCHAR(50) NOT NULL COMMENT '成型机编码',
    `FIXED_STRUCTURE1` VARCHAR(500) DEFAULT NULL COMMENT '固定结构1',
    `FIXED_STRUCTURE2` VARCHAR(500) DEFAULT NULL COMMENT '固定结构2',
    `FIXED_STRUCTURE3` VARCHAR(500) DEFAULT NULL COMMENT '固定结构3',
    `FIXED_MATERIAL_CODE` VARCHAR(1000) DEFAULT NULL COMMENT '固定SKU',
    `FIXED_MATERIAL_DESC` VARCHAR(2000) DEFAULT NULL COMMENT '固定物料描述',
    `DISABLE_STRUCTURE` VARCHAR(1000) DEFAULT NULL COMMENT '不可作业结构',
    `DISABLE_MATERIAL_CODE` VARCHAR(1000) DEFAULT NULL COMMENT '不可作业SKU',
    `DISABLE_MATERIAL_DESC` VARCHAR(2000) DEFAULT NULL COMMENT '不可作业物料描述',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_MACHINE_CODE` (`FACTORY_CODE`, `CX_MACHINE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型固定机台表';

-- ---------------------------------------------------
-- 1.4 成型结构硫化配比表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_STRUCTURE_LH_RATIO`;
CREATE TABLE `T_MDM_STRUCTURE_LH_RATIO` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `CX_MACHINE_TYPE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '机型',
    `STRUCTURE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '结构',
    `LH_MACHINE_MAX_QTY` INT DEFAULT NULL COMMENT '最大硫化机台数',
    `MAX_EMBRYO_QTY` INT DEFAULT NULL COMMENT '最大胎胚数',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_MACHINE_TYPE_STRUCTURE` (`FACTORY_CODE`, `CX_MACHINE_TYPE_CODE`, `STRUCTURE_NAME`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型结构硫化配比表';

-- ---------------------------------------------------
-- 1.5 SKU与施工关系表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_SKU_CONSTRUCTION_REF`;
CREATE TABLE `T_MDM_SKU_CONSTRUCTION_REF` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `MATERIAL_CODE` VARCHAR(50) NOT NULL COMMENT '物料编码',
    `MES_MATERIAL_CODE` VARCHAR(50) DEFAULT NULL COMMENT 'MES物料编码',
    `TRIAL_STATUS` VARCHAR(10) DEFAULT NULL COMMENT '产品状态',
    `SPEC_CODE` VARCHAR(50) DEFAULT NULL COMMENT '规格代号',
    `CONSTRUCTION_CODE` VARCHAR(50) DEFAULT NULL COMMENT '施工代号',
    `EMBRYO_CODE` VARCHAR(50) DEFAULT NULL COMMENT '胎胚号',
    `PRODUCTION_VERSION` VARCHAR(50) DEFAULT NULL COMMENT '生产版本',
    `MOULD_METHOD` VARCHAR(10) DEFAULT NULL COMMENT '成型法',
    `BOM_VERSION` VARCHAR(50) DEFAULT NULL COMMENT 'BOM版本',
    `MOULD_CLAMPING_PRESSURE` DECIMAL(10,2) DEFAULT NULL COMMENT '合模压力',
    `MOULD_CAVITY` VARCHAR(50) DEFAULT NULL COMMENT '模具型腔',
    `IS_ZERO_RACK` VARCHAR(10) DEFAULT NULL COMMENT '是否零度材料',
    `CURING_TIME` INT DEFAULT NULL COMMENT '夏季机械硫化时间(分)',
    `HY_PRESSURE_CURING_TIME` INT DEFAULT NULL COMMENT '夏季液压硫化时间(分)',
    `CURING_TIME2` INT DEFAULT NULL COMMENT '冬季机械硫化时间(分)',
    `HY_PRESSURE_CURING_TIME2` INT DEFAULT NULL COMMENT '冬季液压硫化时间(分)',
    `EMBRYO_NO` VARCHAR(50) DEFAULT NULL COMMENT '制造示方书号',
    `EMBRYO_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '制造示方书类型',
    `EMBRYO_RELEASE_DATE` VARCHAR(50) DEFAULT NULL COMMENT '制造示方书发行时间',
    `TEXT_NO` VARCHAR(50) DEFAULT NULL COMMENT '文字示方书号',
    `TEXT_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '文字示方书类型',
    `TEXT_RELEASE_DATE` VARCHAR(50) DEFAULT NULL COMMENT '文字示方书发行时间',
    `LH_NO` VARCHAR(50) DEFAULT NULL COMMENT '硫化示方书号',
    `LH_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '硫化示方书类型',
    `LH_RELEASE_DATE` VARCHAR(50) DEFAULT NULL COMMENT '硫化示方书发行时间',
    `MAIN_MATERIAL_DESC` VARCHAR(200) DEFAULT NULL COMMENT '主物料(胎胚号)',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    KEY `IDX_MATERIAL_CODE` (`MATERIAL_CODE`),
    KEY `IDX_EMBRYO_CODE` (`EMBRYO_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='SKU与施工关系表';

-- ---------------------------------------------------
-- 1.6 工作日历表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_MDM_WORK_CALENDAR`;
CREATE TABLE `T_MDM_WORK_CALENDAR` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '工厂编号',
    `PROC_CODE` VARCHAR(20) DEFAULT NULL COMMENT '工序编码',
    `YEAR` INT DEFAULT NULL COMMENT '年份',
    `MONTH` INT DEFAULT NULL COMMENT '月份',
    `DAY` INT DEFAULT NULL COMMENT '日期',
    `PRODUCTION_DATE` DATE DEFAULT NULL COMMENT '生产日期',
    `ONE_SHIFT_FLAG` VARCHAR(10) DEFAULT '1' COMMENT '一班开停产标志，0-停,1-开',
    `TWO_SHIFT_FLAG` VARCHAR(10) DEFAULT '1' COMMENT '二班开停产标志，0-停,1-开',
    `THREE_SHIFT_FLAG` VARCHAR(10) DEFAULT '1' COMMENT '三班开停产标志，0-停,1-开',
    `DAY_FLAG` VARCHAR(10) DEFAULT '1' COMMENT '日期开停产标志，0-停,1-开',
    `RATE` INT DEFAULT 100 COMMENT '比例',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_FACTORY_PROC_DATE` (`FACTORY_CODE`, `PROC_CODE`, `PRODUCTION_DATE`),
    KEY `IDX_PRODUCTION_DATE` (`PRODUCTION_DATE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='工作日历表';

-- =====================================================
-- 2. 排程核心表
-- =====================================================

-- ---------------------------------------------------
-- 2.1 成型排程结果表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_CX_SCHEDULE_RESULT`;
CREATE TABLE `T_CX_SCHEDULE_RESULT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '分厂编号',
    `CX_BATCH_NO` VARCHAR(50) DEFAULT NULL COMMENT '成型批次号',
    `ORDER_NO` VARCHAR(50) DEFAULT NULL COMMENT '工单号',
    `PRODUCTION_STATUS` VARCHAR(10) DEFAULT '0' COMMENT '生产状态：0-未生产；1-生产中；2-已收尾',
    `IS_RELEASE` VARCHAR(10) DEFAULT '0' COMMENT '是否发布：0-未发布，1-已发布',
    `SCHEDULE_DATE` DATETIME DEFAULT NULL COMMENT '排程日期',
    `CX_MACHINE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '成型机台编号',
    `CX_MACHINE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '成型机台名称',
    `CX_MACHINE_TYPE` VARCHAR(50) DEFAULT NULL COMMENT '成型机台类型',
    `LH_SCHEDULE_IDS` VARCHAR(500) DEFAULT NULL COMMENT '硫化排程任务序号',
    `LH_MACHINE_CODE` VARCHAR(200) DEFAULT NULL COMMENT '硫化机台编号',
    `LH_MACHINE_NAME` VARCHAR(200) DEFAULT NULL COMMENT '硫化机台名称',
    `LH_MACHINE_QTY` DECIMAL(10,2) DEFAULT NULL COMMENT '硫化机使用总模数',
    `SAP_CODE` VARCHAR(200) DEFAULT NULL COMMENT '外胎代码',
    `SPEC_DESC` VARCHAR(500) DEFAULT NULL COMMENT '外胎规格描述',
    `EMBRYO_CODE` VARCHAR(50) DEFAULT NULL COMMENT '胎胚代码',
    `SPEC_DIMENSION` DECIMAL(10,2) DEFAULT NULL COMMENT '胎胚寸口',
    `STRUCTURE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '结构',
    `TOTAL_STOCK` DECIMAL(10,2) DEFAULT NULL COMMENT '胎胚库存',
    `BOM_DATA_VERSION` VARCHAR(50) DEFAULT NULL COMMENT '施工版本信息',
    `PRODUCT_NUM` DECIMAL(10,2) DEFAULT NULL COMMENT '胎胚总计划量',
    `CLASS1_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '一班计划数',
    `CLASS1_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '一班原因分析手工输入',
    `CLASS1_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '一班完成量',
    `CLASS1_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '一班原因分析',
    `CLASS2_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '二班计划数',
    `CLASS2_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '二班原因分析手工输入',
    `CLASS2_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '二班完成量',
    `CLASS2_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '二班原因分析',
    `CLASS3_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '三班计划数',
    `CLASS3_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '三班原因分析手工输入',
    `CLASS3_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '三班完成量',
    `CLASS3_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '三班原因分析',
    `CLASS4_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '四班计划数',
    `CLASS4_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '四班原因分析手工输入',
    `CLASS4_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '四班完成量',
    `CLASS4_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '四班原因分析',
    `CLASS5_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '五班计划数',
    `CLASS5_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '五班原因分析手工输入',
    `CLASS5_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '五班完成量',
    `CLASS5_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '五班原因分析',
    `CLASS6_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '六班计划数',
    `CLASS6_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '六班原因分析手工输入',
    `CLASS6_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '六班完成量',
    `CLASS6_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '六班原因分析',
    `CLASS7_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '七班计划数',
    `CLASS7_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '七班原因分析手工输入',
    `CLASS7_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '七班完成量',
    `CLASS7_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '七班原因分析',
    `CLASS8_PLAN_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '八班计划数',
    `CLASS8_ANALYSIS_INPUT` VARCHAR(200) DEFAULT NULL COMMENT '八班原因分析手工输入',
    `CLASS8_FINISH_QTY` DECIMAL(10,2) DEFAULT 0 COMMENT '八班完成量',
    `CLASS8_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '八班原因分析',
    `MARK_CLOSE_OUT_TIP` VARCHAR(10) DEFAULT '0' COMMENT '收尾提示标识：0-提示收尾；1-不需要提示',
    `DATA_SOURCE` VARCHAR(10) DEFAULT '0' COMMENT '数据来源：0-自动排程；1-插单；2-导入',
    `SPECIAL_REQUIREMENTS` VARCHAR(500) DEFAULT NULL COMMENT '特殊要求',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    KEY `IDX_BATCH_NO` (`CX_BATCH_NO`),
    KEY `IDX_ORDER_NO` (`ORDER_NO`),
    KEY `IDX_SCHEDULE_DATE` (`SCHEDULE_DATE`),
    KEY `IDX_MACHINE_CODE` (`CX_MACHINE_CODE`),
    KEY `IDX_PRODUCTION_STATUS` (`PRODUCTION_STATUS`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型排程结果表';

-- ---------------------------------------------------
-- 2.2 排程明细表（含车次标识）
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_CX_SCHEDULE_DETAIL`;
CREATE TABLE `T_CX_SCHEDULE_DETAIL` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `MAIN_ID` BIGINT DEFAULT NULL COMMENT '所属主表ID',
    `SCHEDULE_DATE` DATE DEFAULT NULL COMMENT '计划日期',
    `SHIFT_CODE` VARCHAR(20) DEFAULT NULL COMMENT '班次编码',
    `CX_MACHINE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '成型机台编号',
    `CX_MACHINE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '成型机台名称',
    `EMBRYO_CODE` VARCHAR(50) DEFAULT NULL COMMENT '胎胚代码',
    `TRIP_NO` INT DEFAULT NULL COMMENT '车次号',
    `TRIP_CAPACITY` INT DEFAULT NULL COMMENT '本车次容量（条）',
    `TRIP_ACTUAL_QTY` INT DEFAULT NULL COMMENT '本车次实际完成数量',
    `SEQUENCE` INT DEFAULT NULL COMMENT '顺位（全局排序号）',
    `SEQUENCE_IN_GROUP` INT DEFAULT NULL COMMENT '组内顺位',
    `STOCK_HOURS_AT_CALC` DECIMAL(10,2) DEFAULT NULL COMMENT '库存可供硫化时长(小时)',
    `IS_ENDING` INT DEFAULT 0 COMMENT '是否收尾：0-否 1-是',
    `IS_TRIAL` INT DEFAULT 0 COMMENT '是否试制：0-否 1-是',
    `IS_PRECISION` INT DEFAULT 0 COMMENT '是否精度计划：0-否 1-是',
    `IS_CONTINUE` INT DEFAULT 0 COMMENT '是否续作：0-否 1-是',
    `PLAN_START_TIME` DATETIME DEFAULT NULL COMMENT '计划开始时间',
    `PLAN_END_TIME` DATETIME DEFAULT NULL COMMENT '计划结束时间',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    KEY `IDX_MAIN_ID` (`MAIN_ID`),
    KEY `IDX_SCHEDULE_DATE` (`SCHEDULE_DATE`),
    KEY `IDX_MACHINE_CODE` (`CX_MACHINE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='排程明细表';

-- ---------------------------------------------------
-- 2.3 硫化排程结果表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_LH_SCHEDULE_RESULT`;
CREATE TABLE `T_LH_SCHEDULE_RESULT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `FACTORY_CODE` VARCHAR(50) DEFAULT NULL COMMENT '分厂编号',
    `BATCH_NO` VARCHAR(50) DEFAULT NULL COMMENT '批次号',
    `ORDER_NO` VARCHAR(50) DEFAULT NULL COMMENT '工单号',
    `LH_MACHINE_CODE` VARCHAR(50) DEFAULT NULL COMMENT '硫化机台编号',
    `LEFT_RIGHT_MOULD` VARCHAR(10) DEFAULT NULL COMMENT '左右模 L/R/LR',
    `LH_MACHINE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '硫化机台名称',
    `MATERIAL_CODE` VARCHAR(50) DEFAULT NULL COMMENT '物料编号',
    `SPEC_CODE` VARCHAR(50) DEFAULT NULL COMMENT '规格代码',
    `EMBRYO_CODE` VARCHAR(50) DEFAULT NULL COMMENT '胎胚代码',
    `STRUCTURE_NAME` VARCHAR(100) DEFAULT NULL COMMENT '产品结构',
    `MATERIAL_DESC` VARCHAR(200) DEFAULT NULL COMMENT '物料描述',
    `MAIN_MATERIAL_DESC` VARCHAR(200) DEFAULT NULL COMMENT '主物料(胎胚描述)',
    `EMBRYO_STOCK` INT DEFAULT NULL COMMENT '胎胚库存',
    `SPEC_DESC` VARCHAR(200) DEFAULT NULL COMMENT '规格描述',
    `LH_TIME` INT DEFAULT NULL COMMENT '硫化时长 单位：秒',
    `DAILY_PLAN_QTY` INT DEFAULT NULL COMMENT '日计划数量',
    `SCHEDULE_DATE` DATE DEFAULT NULL COMMENT '排程日期',
    `SPEC_END_TIME` DATETIME DEFAULT NULL COMMENT '规格结束时间',
    `PRODUCTION_STATUS` VARCHAR(10) DEFAULT '0' COMMENT '生产状态',
    `CLASS1_PLAN_QTY` INT DEFAULT 0 COMMENT '1班计划量',
    `CLASS1_START_TIME` DATETIME DEFAULT NULL COMMENT '1班开始时间',
    `CLASS1_END_TIME` DATETIME DEFAULT NULL COMMENT '1班结束时间',
    `CLASS1_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '1班原因分析',
    `CLASS1_FINISH_QTY` INT DEFAULT 0 COMMENT '1班完成量',
    `CLASS2_PLAN_QTY` INT DEFAULT 0 COMMENT '2班计划量',
    `CLASS2_START_TIME` DATETIME DEFAULT NULL COMMENT '2班开始时间',
    `CLASS2_END_TIME` DATETIME DEFAULT NULL COMMENT '2班结束时间',
    `CLASS2_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '2班原因分析',
    `CLASS2_FINISH_QTY` INT DEFAULT 0 COMMENT '2班完成量',
    `CLASS3_PLAN_QTY` INT DEFAULT 0 COMMENT '3班计划量',
    `CLASS3_START_TIME` DATETIME DEFAULT NULL COMMENT '3班开始时间',
    `CLASS3_END_TIME` DATETIME DEFAULT NULL COMMENT '3班结束时间',
    `CLASS3_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '3班原因分析',
    `CLASS3_FINISH_QTY` INT DEFAULT 0 COMMENT '3班完成量',
    `CLASS4_PLAN_QTY` INT DEFAULT 0 COMMENT '4班计划量',
    `CLASS4_START_TIME` DATETIME DEFAULT NULL COMMENT '4班开始时间',
    `CLASS4_END_TIME` DATETIME DEFAULT NULL COMMENT '4班结束时间',
    `CLASS4_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '4班原因分析',
    `CLASS4_FINISH_QTY` INT DEFAULT 0 COMMENT '4班完成量',
    `CLASS5_PLAN_QTY` INT DEFAULT 0 COMMENT '5班计划量',
    `CLASS5_START_TIME` DATETIME DEFAULT NULL COMMENT '5班开始时间',
    `CLASS5_END_TIME` DATETIME DEFAULT NULL COMMENT '5班结束时间',
    `CLASS5_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '5班原因分析',
    `CLASS5_FINISH_QTY` INT DEFAULT 0 COMMENT '5班完成量',
    `CLASS6_PLAN_QTY` INT DEFAULT 0 COMMENT '6班计划量',
    `CLASS6_START_TIME` DATETIME DEFAULT NULL COMMENT '6班开始时间',
    `CLASS6_END_TIME` DATETIME DEFAULT NULL COMMENT '6班结束时间',
    `CLASS6_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '6班原因分析',
    `CLASS6_FINISH_QTY` INT DEFAULT 0 COMMENT '6班完成量',
    `CLASS7_PLAN_QTY` INT DEFAULT 0 COMMENT '7班计划量',
    `CLASS7_START_TIME` DATETIME DEFAULT NULL COMMENT '7班开始时间',
    `CLASS7_END_TIME` DATETIME DEFAULT NULL COMMENT '7班结束时间',
    `CLASS7_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '7班原因分析',
    `CLASS7_FINISH_QTY` INT DEFAULT 0 COMMENT '7班完成量',
    `CLASS8_PLAN_QTY` INT DEFAULT 0 COMMENT '8班计划量',
    `CLASS8_START_TIME` DATETIME DEFAULT NULL COMMENT '8班开始时间',
    `CLASS8_END_TIME` DATETIME DEFAULT NULL COMMENT '8班结束时间',
    `CLASS8_ANALYSIS` VARCHAR(200) DEFAULT NULL COMMENT '8班原因分析',
    `CLASS8_FINISH_QTY` INT DEFAULT 0 COMMENT '8班完成量',
    `IS_DELIVERY` VARCHAR(10) DEFAULT '0' COMMENT '是否交期：0-否 1-是',
    `IS_RELEASE` VARCHAR(10) DEFAULT '0' COMMENT '是否发布',
    `PUBLISH_SUCCESS_COUNT` DECIMAL(10,2) DEFAULT NULL COMMENT '发布成功计数',
    `NEWEST_PUBLISH_TIME` DATETIME DEFAULT NULL COMMENT '最新发布时间',
    `DATA_SOURCE` VARCHAR(10) DEFAULT '0' COMMENT '数据来源',
    `MOULD_QTY` INT DEFAULT NULL COMMENT '使用模数',
    `SINGLE_MOULD_SHIFT_QTY` INT DEFAULT NULL COMMENT '单班硫化量',
    `MOULD_INFO` TEXT DEFAULT NULL COMMENT '模具信息 JSON字符串',
    `MOULD_METHOD` VARCHAR(10) DEFAULT NULL COMMENT '硫化方式',
    `CONSTRUCTION_STAGE` VARCHAR(50) DEFAULT NULL COMMENT '施工阶段',
    `EMBRYO_NO` VARCHAR(50) DEFAULT NULL COMMENT '制造示方书号',
    `TEXT_NO` VARCHAR(50) DEFAULT NULL COMMENT '文字示方书号',
    `LH_NO` VARCHAR(50) DEFAULT NULL COMMENT '硫化示方书号',
    `MONTH_PLAN_VERSION` VARCHAR(50) DEFAULT NULL COMMENT '月计划版本',
    `MACHINE_ORDER` INT DEFAULT NULL COMMENT '机台排序号',
    `IS_TRIAL` VARCHAR(10) DEFAULT '0' COMMENT '是否试制量试',
    `REAL_SCHEDULE_DATE` DATE DEFAULT NULL COMMENT '实际排程日期',
    `TDAY_SPEC_END_TIME` DATETIME DEFAULT NULL COMMENT 'T日规格结束时间',
    `IS_FIRST` VARCHAR(10) DEFAULT '0' COMMENT '是否首排',
    `MOULD_SURPLUS_QTY` INT DEFAULT NULL COMMENT '硫化余量',
    `IS_END` VARCHAR(10) DEFAULT '0' COMMENT '是否收尾',
    `PRODUCTION_VERSION` VARCHAR(50) DEFAULT NULL COMMENT '排产版本',
    `MOULD_CODE` VARCHAR(200) DEFAULT NULL COMMENT '模具号',
    `IS_SPLIT` VARCHAR(10) DEFAULT '0' COMMENT '是否拆分',
    `SCHEDULE_ORDER` VARCHAR(50) DEFAULT NULL COMMENT '排程顺序',
    `SCHEDULE_TYPE` VARCHAR(10) DEFAULT NULL COMMENT '排程类型 01-续作 02-新增',
    `IS_CHANGE_MOULD` VARCHAR(10) DEFAULT '0' COMMENT '是否换模',
    `TOTAL_DAILY_PLAN_QTY` INT DEFAULT NULL COMMENT '总计划数量',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    KEY `IDX_BATCH_NO` (`BATCH_NO`),
    KEY `IDX_ORDER_NO` (`ORDER_NO`),
    KEY `IDX_SCHEDULE_DATE` (`SCHEDULE_DATE`),
    KEY `IDX_LH_MACHINE_CODE` (`LH_MACHINE_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='硫化排程结果表';

-- =====================================================
-- 3. 配置与库存表
-- =====================================================

-- ---------------------------------------------------
-- 3.1 班次配置表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_CX_SHIFT_CONFIG`;
CREATE TABLE `T_CX_SHIFT_CONFIG` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `SHIFT_CODE` VARCHAR(20) NOT NULL COMMENT '班次编码',
    `SHIFT_NAME` VARCHAR(50) DEFAULT NULL COMMENT '班次名称',
    `START_TIME` TIME DEFAULT NULL COMMENT '开始时间',
    `END_TIME` TIME DEFAULT NULL COMMENT '结束时间',
    `SORT_ORDER` INT DEFAULT NULL COMMENT '排序',
    `IS_ACTIVE` INT DEFAULT 1 COMMENT '是否启用',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_SHIFT_CODE` (`SHIFT_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='班次配置表';

-- ---------------------------------------------------
-- 3.2 成型参数配置表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_CX_PARAMS`;
CREATE TABLE `T_CX_PARAMS` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `CONFIG_CODE` VARCHAR(50) NOT NULL COMMENT '配置编码',
    `CONFIG_NAME` VARCHAR(100) DEFAULT NULL COMMENT '配置名称',
    `CONFIG_VALUE` VARCHAR(500) DEFAULT NULL COMMENT '配置值',
    `CONFIG_TYPE` VARCHAR(20) DEFAULT 'STRING' COMMENT '配置类型：NUMBER/STRING/DATE/BOOLEAN',
    `CONFIG_UNIT` VARCHAR(20) DEFAULT NULL COMMENT '单位',
    `DESCRIPTION` VARCHAR(500) DEFAULT NULL COMMENT '配置说明',
    `IS_ACTIVE` INT DEFAULT 1 COMMENT '是否启用：0-禁用 1-启用',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_CONFIG_CODE` (`CONFIG_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型参数配置表';

-- ---------------------------------------------------
-- 3.3 成型库存信息表
-- ---------------------------------------------------
DROP TABLE IF EXISTS `T_CX_STOCK`;
CREATE TABLE `T_CX_STOCK` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `STOCK_DATE` DATE DEFAULT NULL COMMENT '库存日期',
    `BOM_DATA_VERSION` VARCHAR(50) DEFAULT NULL COMMENT '施工版本信息',
    `EMBRYO_CODE` VARCHAR(50) NOT NULL COMMENT '胎胚代码',
    `SCHEDULE_USE_STOCK` BIGINT DEFAULT 0 COMMENT '排程使用库存',
    `STOCK_NUM` BIGINT DEFAULT 0 COMMENT '库存量(可用)',
    `UNAVAILABLE_STOCK` BIGINT DEFAULT 0 COMMENT '库存量(不可用)',
    `OVER_TIME_STOCK` BIGINT DEFAULT 0 COMMENT '超期库存',
    `MODIFY_NUM` BIGINT DEFAULT 0 COMMENT '修正数量',
    `BAD_NUM` BIGINT DEFAULT 0 COMMENT '不良数量',
    `CREATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '创建人',
    `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `UPDATE_BY` VARCHAR(64) DEFAULT NULL COMMENT '更新人',
    `UPDATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    `REMARK` VARCHAR(500) DEFAULT NULL COMMENT '备注',
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_DATE_EMBRYO` (`STOCK_DATE`, `EMBRYO_CODE`),
    KEY `IDX_STOCK_DATE` (`STOCK_DATE`),
    KEY `IDX_EMBRYO_CODE` (`EMBRYO_CODE`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='成型库存信息表';

-- =====================================================
-- 4. 初始化数据
-- =====================================================

-- 初始化班次配置
INSERT INTO `T_CX_SHIFT_CONFIG` (`SHIFT_CODE`, `SHIFT_NAME`, `START_TIME`, `END_TIME`, `SORT_ORDER`, `IS_ACTIVE`) VALUES
('NIGHT', '夜班', '00:00:00', '08:00:00', 1, 1),
('DAY', '早班', '08:00:00', '16:00:00', 2, 1),
('AFTERNOON', '中班', '16:00:00', '24:00:00', 3, 1);

-- 初始化参数配置
INSERT INTO `T_CX_PARAMS` (`CONFIG_CODE`, `CONFIG_NAME`, `CONFIG_VALUE`, `CONFIG_TYPE`, `CONFIG_UNIT`, `DESCRIPTION`, `IS_ACTIVE`) VALUES
('STOCK_WARNING_HOURS', '库存预警时长', '8', 'NUMBER', '小时', '当库存可供硫化时长低于此值时触发预警', 1),
('MAX_TRIP_CAPACITY', '最大车次容量', '50', 'NUMBER', '条', '单次车次最大运输量', 1),
('SCHEDULE_DAYS_AHEAD', '排程提前天数', '3', 'NUMBER', '天', '排程覆盖的未来天数', 1);

SET FOREIGN_KEY_CHECKS = 1;
