-- 结构班产配置表
-- 定义每个结构在各班次的标准产能（整车条数）
CREATE TABLE IF NOT EXISTS T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    STRUCTURE_CODE VARCHAR(50) NOT NULL COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) COMMENT '结构名称',
    MACHINE_TYPE_CODE VARCHAR(50) COMMENT '机型编码',
    SHIFT_CODE VARCHAR(20) NOT NULL COMMENT '班次编码：NIGHT(夜班)/DAY(早班)/AFTERNOON(中班)',
    SHIFT_NAME VARCHAR(50) COMMENT '班次名称',
    TRIP_QTY INT DEFAULT 0 COMMENT '整车条数（以整车为单位，1车=12条）',
    STANDARD_CAPACITY INT COMMENT '标准产能（条）= 整车条数 × 12',
    CAPACITY_PER_HOUR DECIMAL(10,2) COMMENT '每小时产能（条/小时）',
    MIN_CAPACITY INT COMMENT '最小产能（条）',
    MAX_CAPACITY INT COMMENT '最大产能（条）',
    IS_ACTIVE TINYINT DEFAULT 1 COMMENT '是否启用：0-禁用 1-启用',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    UNIQUE KEY UK_STRUCTURE_SHIFT (STRUCTURE_CODE, SHIFT_CODE, MACHINE_TYPE_CODE),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE),
    KEY IDX_SHIFT_CODE (SHIFT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='结构班产配置表';

-- 初始化示例数据
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY 
(STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE_CODE, SHIFT_CODE, SHIFT_NAME, TRIP_QTY, STANDARD_CAPACITY, CAPACITY_PER_HOUR, IS_ACTIVE, REMARK) VALUES
-- 结构A示例
('A001', '结构A', 'TYPE_1', 'SHIFT_NIGHT', '夜班', 8, 96, 12.00, 1, '夜班标准产能8车=96条'),
('A001', '结构A', 'TYPE_1', 'SHIFT_DAY', '早班', 16, 192, 24.00, 1, '早班标准产能16车=192条'),
('A001', '结构A', 'TYPE_1', 'SHIFT_AFTERNOON', '中班', 8, 96, 12.00, 1, '中班标准产能8车=96条'),
-- 结构B示例
('B001', '结构B', 'TYPE_1', 'SHIFT_NIGHT', '夜班', 10, 120, 15.00, 1, '夜班标准产能10车=120条'),
('B001', '结构B', 'TYPE_1', 'SHIFT_DAY', '早班', 20, 240, 30.00, 1, '早班标准产能20车=240条'),
('B001', '结构B', 'TYPE_1', 'SHIFT_AFTERNOON', '中班', 10, 120, 15.00, 1, '中班标准产能10车=120条');
