-- 结构班产配置表
-- 定义每个结构在每台成型机上的整车条数
-- 整车条数按结构不同而不同，可能是12条、18条等
CREATE TABLE IF NOT EXISTS T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    STRUCTURE_CODE VARCHAR(50) NOT NULL COMMENT '结构编码',
    TRIP_QTY INT NOT NULL COMMENT '整车条数（该结构每车的条数，可能是12、18等）',
    CX_MACHINE_CODE VARCHAR(50) NOT NULL COMMENT '成型机台编码',
    IS_ACTIVE TINYINT DEFAULT 1 COMMENT '是否启用：0-禁用 1-启用',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    UNIQUE KEY UK_STRUCTURE_MACHINE (STRUCTURE_CODE, CX_MACHINE_CODE),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE),
    KEY IDX_CX_MACHINE_CODE (CX_MACHINE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='结构班产配置表-整车条数配置';

-- 初始化示例数据
-- 不同结构的整车条数可能不同，如12条、18条等
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY 
(STRUCTURE_CODE, TRIP_QTY, CX_MACHINE_CODE, IS_ACTIVE) VALUES
-- 结构A，整车12条
('A001', 12, 'CX-001', 1),
('A001', 12, 'CX-002', 1),
('A001', 12, 'CX-003', 1),
-- 结构B，整车18条
('B001', 18, 'CX-001', 1),
('B001', 18, 'CX-002', 1),
-- 结构C，整车15条
('C001', 15, 'CX-001', 1);
