-- 关键产品配置表
-- 定义关键产品列表，用于开产首班排除等场景判断
CREATE TABLE IF NOT EXISTS T_CX_KEY_PRODUCT (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '主键ID',
    EMBRYO_CODE VARCHAR(50) NOT NULL COMMENT '胎胚编码',
    EMBRYO_NAME VARCHAR(100) COMMENT '胎胚名称',
    STRUCTURE_CODE VARCHAR(50) COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) COMMENT '结构名称',
    PRIORITY INT DEFAULT 0 COMMENT '优先级',
    IS_ACTIVE TINYINT DEFAULT 1 COMMENT '是否启用：0-禁用 1-启用',
    REMARK VARCHAR(500) COMMENT '备注',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    
    UNIQUE KEY UK_EMBRYO_CODE (EMBRYO_CODE),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='关键产品配置表';

-- 初始化示例数据
INSERT INTO T_CX_KEY_PRODUCT 
(EMBRYO_CODE, EMBRYO_NAME, STRUCTURE_CODE, STRUCTURE_NAME, PRIORITY, IS_ACTIVE, REMARK) VALUES
('TE001', '胎胚001', 'A001', '结构A', 10, 1, '关键产品-主销型号'),
('TE002', '胎胚002', 'A001', '结构A', 10, 1, '关键产品-主销型号'),
('TE003', '胎胚003', 'B001', '结构B', 8, 1, '关键产品');
