-- ============================================
-- APS成型排程系统数据库初始化脚本
-- 用于补充缺失的表结构和数据
-- ============================================

-- ---------------------------------------------
-- 1. T_CX_PARAM_CONFIG - 参数配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_PARAM_CONFIG (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    PARAM_CODE VARCHAR(50) NOT NULL COMMENT '参数编码',
    PARAM_NAME VARCHAR(100) NOT NULL COMMENT '参数名称',
    PARAM_VALUE VARCHAR(500) DEFAULT NULL COMMENT '参数值',
    GROUP_CODE VARCHAR(50) DEFAULT NULL COMMENT '分组编码',
    GROUP_NAME VARCHAR(100) DEFAULT NULL COMMENT '分组名称',
    SORT_ORDER INT DEFAULT 0 COMMENT '排序号',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_ACTIVE TINYINT(1) DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_PARAM_CODE (PARAM_CODE, FACTORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='参数配置表';

-- 插入默认参数配置
INSERT INTO T_CX_PARAM_CONFIG (PARAM_CODE, PARAM_NAME, PARAM_VALUE, GROUP_CODE, GROUP_NAME, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'LOSS_RATE', '损耗率', '0.02', 'PRODUCTION', '生产参数', '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_PARAM_CONFIG WHERE PARAM_CODE = 'LOSS_RATE' AND FACTORY_CODE = '116');

INSERT INTO T_CX_PARAM_CONFIG (PARAM_CODE, PARAM_NAME, PARAM_VALUE, GROUP_CODE, GROUP_NAME, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'MAX_TYPES_PER_MACHINE', '机台种类上限', '4', 'PRODUCTION', '生产参数', '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_PARAM_CONFIG WHERE PARAM_CODE = 'MAX_TYPES_PER_MACHINE' AND FACTORY_CODE = '116');

INSERT INTO T_CX_PARAM_CONFIG (PARAM_CODE, PARAM_NAME, PARAM_VALUE, GROUP_CODE, GROUP_NAME, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'DEFAULT_TRIP_CAPACITY', '默认整车容量', '200', 'PRODUCTION', '生产参数', '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_PARAM_CONFIG WHERE PARAM_CODE = 'DEFAULT_TRIP_CAPACITY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_PARAM_CONFIG (PARAM_CODE, PARAM_NAME, PARAM_VALUE, GROUP_CODE, GROUP_NAME, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'SHIFT_TYPE_DIFF_THRESHOLD', '种类差额阈值', '1', 'BALANCE', '均衡参数', '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_PARAM_CONFIG WHERE PARAM_CODE = 'SHIFT_TYPE_DIFF_THRESHOLD' AND FACTORY_CODE = '116');

INSERT INTO T_CX_PARAM_CONFIG (PARAM_CODE, PARAM_NAME, PARAM_VALUE, GROUP_CODE, GROUP_NAME, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'SHIFT_LOAD_DIFF_THRESHOLD', '负荷差额阈值', '3', 'BALANCE', '均衡参数', '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_PARAM_CONFIG WHERE PARAM_CODE = 'SHIFT_LOAD_DIFF_THRESHOLD' AND FACTORY_CODE = '116');

-- ---------------------------------------------
-- 2. T_CX_SHIFT_CONFIG - 班次配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_SHIFT_CONFIG (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    SHIFT_CODE VARCHAR(20) NOT NULL COMMENT '班次编码',
    SHIFT_NAME VARCHAR(50) NOT NULL COMMENT '班次名称',
    START_TIME VARCHAR(10) DEFAULT NULL COMMENT '开始时间',
    END_TIME VARCHAR(10) DEFAULT NULL COMMENT '结束时间',
    DURATION_HOURS DECIMAL(4,2) DEFAULT NULL COMMENT '持续时长(小时)',
    CAPACITY_RATIO DECIMAL(5,2) DEFAULT 1.00 COMMENT '产能比例',
    FACTORY_CODE VARCHAR(20) NOT NULL COMMENT '工厂编码',
    IS_ACTIVE TINYINT(1) DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_SHIFT_CODE_FACTORY (SHIFT_CODE, FACTORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='班次配置表';

-- 插入默认班次配置（夜班、早班、中班）
INSERT INTO T_CX_SHIFT_CONFIG (SHIFT_CODE, SHIFT_NAME, START_TIME, END_TIME, DURATION_HOURS, CAPACITY_RATIO, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'NIGHT', '夜班', '23:00', '07:00', 8.00, 1.00, '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_SHIFT_CONFIG WHERE SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116');

INSERT INTO T_CX_SHIFT_CONFIG (SHIFT_CODE, SHIFT_NAME, START_TIME, END_TIME, DURATION_HOURS, CAPACITY_RATIO, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'DAY', '早班', '07:00', '15:00', 8.00, 2.00, '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_SHIFT_CONFIG WHERE SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_SHIFT_CONFIG (SHIFT_CODE, SHIFT_NAME, START_TIME, END_TIME, DURATION_HOURS, CAPACITY_RATIO, FACTORY_CODE, IS_ACTIVE, IS_DELETE)
SELECT 'AFTERNOON', '中班', '15:00', '23:00', 8.00, 1.00, '116', 1, '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_SHIFT_CONFIG WHERE SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116');

-- ---------------------------------------------
-- 3. T_CX_STRUCTURE_SHIFT_CAPACITY - 结构班次产能配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    STRUCTURE_CODE VARCHAR(50) NOT NULL COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) NOT NULL COMMENT '结构名称',
    MACHINE_TYPE VARCHAR(50) DEFAULT NULL COMMENT '机台类型',
    SHIFT_CODE VARCHAR(20) DEFAULT NULL COMMENT '班次编码',
    HOURLY_CAPACITY INT DEFAULT NULL COMMENT '小时产能(条)',
    DAILY_CAPACITY INT DEFAULT NULL COMMENT '日产能(条)',
    TREAD_COUNT INT DEFAULT NULL COMMENT '胎面整车条数',
    FACTORY_CODE VARCHAR(20) NOT NULL COMMENT '工厂编码',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE),
    KEY IDX_FACTORY_CODE (FACTORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='结构班次产能配置表';

-- ---------------------------------------------
-- 4. t_mdm_structure_tread_config - 结构整车配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS t_mdm_structure_tread_config (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    STRUCTURE_CODE VARCHAR(50) NOT NULL COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) NOT NULL COMMENT '结构名称',
    TREAD_COUNT INT DEFAULT NULL COMMENT '胎面整车条数',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='结构整车配置表';

-- ---------------------------------------------
-- 5. T_MDM_STRUCTURE_LH_RATIO - 结构硫化配比表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_MDM_STRUCTURE_LH_RATIO (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    STRUCTURE_CODE VARCHAR(50) NOT NULL COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) DEFAULT NULL COMMENT '结构名称',
    RATIO DECIMAL(5,2) DEFAULT NULL COMMENT '配比值',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='结构硫化配比表';

-- ---------------------------------------------
-- 6. T_CX_KEY_PRODUCT - 关键产品配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_KEY_PRODUCT (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    EMBRYO_CODE VARCHAR(50) NOT NULL COMMENT '胎胚编码',
    EMBRYO_NAME VARCHAR(100) DEFAULT NULL COMMENT '胎胚名称',
    STRUCTURE_CODE VARCHAR(50) DEFAULT NULL COMMENT '结构编码',
    STRUCTURE_NAME VARCHAR(100) DEFAULT NULL COMMENT '结构名称',
    PRIORITY INT DEFAULT 0 COMMENT '优先级',
    REASON VARCHAR(500) DEFAULT NULL COMMENT '关键原因',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_ACTIVE TINYINT(1) DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    KEY IDX_EMBRYO_CODE (EMBRYO_CODE),
    KEY IDX_STRUCTURE_CODE (STRUCTURE_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='关键产品配置表';

-- ---------------------------------------------
-- 7. T_CX_HOLIDAY_CONFIG - 节假日配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_HOLIDAY_CONFIG (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    HOLIDAY_DATE DATE NOT NULL COMMENT '节假日日期',
    HOLIDAY_NAME VARCHAR(100) NOT NULL COMMENT '节假日名称',
    HOLIDAY_TYPE VARCHAR(20) DEFAULT NULL COMMENT '节假日类型：HOLIDAY-节假日，WORKDAY-工作日',
    EFFECT_FLAG CHAR(1) DEFAULT '1' COMMENT '生效标志：0-不生效，1-生效',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_HOLIDAY_DATE (HOLIDAY_DATE, FACTORY_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='节假日配置表';

-- ---------------------------------------------
-- 8. T_CX_ALERT_CONFIG - 预警配置表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS T_CX_ALERT_CONFIG (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    ALERT_CODE VARCHAR(50) NOT NULL COMMENT '预警编码',
    ALERT_NAME VARCHAR(100) NOT NULL COMMENT '预警名称',
    ALERT_TYPE VARCHAR(20) DEFAULT NULL COMMENT '预警类型',
    THRESHOLD_VALUE VARCHAR(50) DEFAULT NULL COMMENT '阈值',
    ALERT_LEVEL VARCHAR(20) DEFAULT NULL COMMENT '预警级别',
    FACTORY_CODE VARCHAR(20) DEFAULT NULL COMMENT '工厂编码',
    IS_ACTIVE TINYINT(1) DEFAULT 1 COMMENT '是否启用：0-禁用，1-启用',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_BY VARCHAR(64) DEFAULT NULL COMMENT '创建者',
    CREATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_BY VARCHAR(64) DEFAULT NULL COMMENT '更新者',
    UPDATE_TIME DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (ID),
    UNIQUE KEY UK_ALERT_CODE (ALERT_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='预警配置表';

-- ---------------------------------------------
-- 9. t_mdm_sku_lh_capacity - SKU日硫化产能表
-- ---------------------------------------------
CREATE TABLE IF NOT EXISTS t_mdm_sku_lh_capacity (
    ID BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    FACTORY_CODE VARCHAR(20) NOT NULL COMMENT '工厂编号',
    MES_MATERIAL_CODE VARCHAR(30) DEFAULT NULL COMMENT 'MES物料编码',
    MATERIAL_CODE VARCHAR(30) NOT NULL COMMENT '物料编码',
    MATERIAL_DESC VARCHAR(256) DEFAULT NULL COMMENT '物料描述',
    CLASS_CAPACITY DECIMAL(8,0) DEFAULT NULL COMMENT '班产',
    MES_CAPACITY DECIMAL(8,0) DEFAULT NULL COMMENT 'MES实际产量',
    STANDARD_CAPACITY DECIMAL(8,0) DEFAULT NULL COMMENT '标准产能',
    APS_CAPACITY DECIMAL(8,0) DEFAULT NULL COMMENT 'APS计算日硫化量',
    SUM_VULCANIZATION DECIMAL(8,0) DEFAULT NULL COMMENT '硫化总时间(min)',
    VULCANIZATION_TIME DECIMAL(8,0) DEFAULT NULL COMMENT '硫化总时间(s)',
    MECHANICAL_TIME DECIMAL(8,0) DEFAULT '0' COMMENT '机械动作时(s)',
    CHECK_TIME DECIMAL(8,0) DEFAULT '0' COMMENT '点检时间',
    CLEAR_TIME DECIMAL(8,0) DEFAULT NULL COMMENT '检查胶囊、喷胶膜、模具清理2次',
    PRODUCTION_TIME DECIMAL(8,0) DEFAULT NULL COMMENT '生产作业时间(s)',
    STANDARD_TIME DECIMAL(8,0) DEFAULT NULL COMMENT '标准作业时间(s)',
    DINE_TIME DECIMAL(8,0) DEFAULT NULL COMMENT '就餐时间',
    REMARK VARCHAR(500) DEFAULT NULL COMMENT '备注',
    IS_DELETE CHAR(1) DEFAULT '0' COMMENT '是否删除：0-未删除，1-已删除',
    CREATE_TIME TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    UPDATE_TIME TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    CREATE_BY VARCHAR(20) DEFAULT NULL COMMENT '创建人',
    UPDATE_BY VARCHAR(20) DEFAULT NULL COMMENT '修改人',
    PRIMARY KEY (ID),
    KEY IDX_FACTORY_CODE (FACTORY_CODE),
    KEY IDX_PRODUCT_CODE (MATERIAL_CODE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='SKU日硫化产能表';

-- ---------------------------------------------
-- 10. T_MDM_MOLDING_MACHINE - 成型机台表
-- ---------------------------------------------
-- 注意：如果表已存在，跳过创建
-- 请确保 IS_ONLINE = 1 和 IS_ACTIVE = 1 的机台才是可用机台
UPDATE T_MDM_MOLDING_MACHINE SET IS_ONLINE = 1, IS_ACTIVE = 1, IS_DELETE = '0' WHERE IS_DELETE = '0';

-- ---------------------------------------------
-- 验证查询
-- ---------------------------------------------
SELECT 'T_CX_PARAM_CONFIG' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM T_CX_PARAM_CONFIG WHERE IS_DELETE = '0'
UNION ALL
SELECT 'T_CX_SHIFT_CONFIG', COUNT(*) FROM T_CX_SHIFT_CONFIG WHERE IS_DELETE = '0'
UNION ALL
SELECT 'T_CX_STRUCTURE_SHIFT_CAPACITY', COUNT(*) FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE IS_DELETE = '0'
UNION ALL
SELECT 't_mdm_structure_tread_config', COUNT(*) FROM t_mdm_structure_tread_config WHERE IS_DELETE = '0'
UNION ALL
SELECT 'T_MDM_STRUCTURE_LH_RATIO', COUNT(*) FROM T_MDM_STRUCTURE_LH_RATIO WHERE IS_DELETE = '0'
UNION ALL
SELECT 'T_CX_KEY_PRODUCT', COUNT(*) FROM T_CX_KEY_PRODUCT WHERE IS_DELETE = '0'
UNION ALL
SELECT 'T_CX_HOLIDAY_CONFIG', COUNT(*) FROM T_CX_HOLIDAY_CONFIG WHERE IS_DELETE = '0'
UNION ALL
SELECT 't_mdm_sku_lh_capacity', COUNT(*) FROM t_mdm_sku_lh_capacity WHERE IS_DELETE = '0';
