-- ============================================
-- APS成型排程系统测试数据
-- 基于实体类完整字段生成
-- ============================================

-- ---------------------------------------------
-- 1. T_MP_STRUCTURE_ALLOCATION - 结构排产配置
-- ---------------------------------------------

-- 结构1: 215/75R17.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE,
    YEAR, MONTH, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_T_MP_STRUCTURE_ALLOCATION.NEXTVAL,
    '215/75R17.5', '215/75R17.5', CX_MACHINE_CODE, '成型',
    2026, 3, 1, 31, 31,
    '116', '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-215/75R17.5'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1201', 'H1202', 'H1203', 'H1204', 'H1205', 'H1206')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_CODE = '215/75R17.5'
);

-- 结构2: 10R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE,
    YEAR, MONTH, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_T_MP_STRUCTURE_ALLOCATION.NEXTVAL,
    '10R22.5', '10R22.5', CX_MACHINE_CODE, '成型',
    2026, 3, 1, 31, 31,
    '116', '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-10R22.5'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1207', 'H1208', 'H1209', 'H1210', 'H1211', 'H1212')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_CODE = '10R22.5'
);

-- 结构3: 11R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE,
    YEAR, MONTH, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_T_MP_STRUCTURE_ALLOCATION.NEXTVAL,
    '11R22.5', '11R22.5', CX_MACHINE_CODE, '成型',
    2026, 3, 1, 31, 31,
    '116', '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-11R22.5'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1213', 'H1214', 'H1215', 'H1216', 'H1217', 'H1218')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_CODE = '11R22.5'
);

-- 结构4: 12R22.5 (7台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE,
    YEAR, MONTH, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_T_MP_STRUCTURE_ALLOCATION.NEXTVAL,
    '12R22.5', '12R22.5', CX_MACHINE_CODE, '成型',
    2026, 3, 1, 31, 31,
    '116', '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-12R22.5'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1219', 'H1220', 'H1221', 'H1222', 'H1223', 'H1224', 'H1225')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_CODE = '12R22.5'
);

-- ---------------------------------------------
-- 2. t_mdm_structure_tread_config - 结构整车配置
-- ---------------------------------------------
-- 字段: ID, STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK

INSERT INTO t_mdm_structure_tread_config (
    ID, STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_t_mdm_structure_tread_config.NEXTVAL,
    '215/75R17.5', 200, '1.0', 'C001', '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-215/75R17.5'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '215/75R17.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    ID, STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_t_mdm_structure_tread_config.NEXTVAL,
    '10R22.5', 200, '1.0', 'C001', '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-10R22.5'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '10R22.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    ID, STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_t_mdm_structure_tread_config.NEXTVAL,
    '11R22.5', 200, '1.0', 'C001', '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-11R22.5'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '11R22.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    ID, STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 
    SEQ_t_mdm_structure_tread_config.NEXTVAL,
    '12R22.5', 200, '1.0', 'C001', '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '测试数据-12R22.5'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '12R22.5' AND FACTORY_CODE = '116'
);

-- ---------------------------------------------
-- 3. T_CX_STRUCTURE_SHIFT_CAPACITY - 结构班次产能配置
-- ---------------------------------------------
-- 字段: ID, STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK

-- 215/75R17.5 班次产能
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 1, '215/75R17.5', '215/75R17.5', '成型', 'NIGHT', 24, 192, 200, '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '夜班产能'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116'
);

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 2, '215/75R17.5', '215/75R17.5', '成型', 'DAY', 48, 384, 200, '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '早班产能'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116'
);

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (
    ID, STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE,
    IS_DELETE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
)
SELECT 3, '215/75R17.5', '215/75R17.5', '成型', 'AFTERNOON', 24, 192, 200, '116',
    '0', 'admin', SYSDATE, 'admin', SYSDATE, '中班产能'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116'
);

-- ---------------------------------------------
-- 4. 验证查询
-- ---------------------------------------------
SELECT STRUCTURE_NAME, COUNT(*) AS MACHINE_COUNT
FROM T_MP_STRUCTURE_ALLOCATION
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0'
GROUP BY STRUCTURE_NAME
ORDER BY STRUCTURE_NAME;
