-- ============================================
-- APS成型排程系统测试数据
-- 用于验证排程功能的合理性
-- ============================================

-- ---------------------------------------------
-- 1. T_MP_STRUCTURE_ALLOCATION - 结构排产配置
-- 为25台机台配置合理的产能分配
-- ---------------------------------------------

-- 清空现有数据（测试用）
-- DELETE FROM T_MP_STRUCTURE_ALLOCATION WHERE FACTORY_CODE = '116';

-- 插入测试数据：25台机台，分配到4个结构
-- 每个结构分配6-7台机台
-- 每台机台的MAX_LH设置为2（表示该机台最多同时生产2个硫化任务）

-- 结构1: 215/75R17.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE, YEAR, MONTH, BEGIN_DAY, END_DAY, MAX_LH, FACTORY_CODE, IS_DELETE)
SELECT '215/75R17.5', '215/75R17.5', CX_MACHINE_CODE, '成型', 2026, 3, 1, 31, 2, '116', '0'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1201', 'H1202', 'H1203', 'H1204', 'H1205', 'H1206')
AND NOT EXISTS (SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE AND FACTORY_CODE = '116');

-- 结构2: 10R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE, YEAR, MONTH, BEGIN_DAY, END_DAY, MAX_LH, FACTORY_CODE, IS_DELETE)
SELECT '10R22.5', '10R22.5', CX_MACHINE_CODE, '成型', 2026, 3, 1, 31, 2, '116', '0'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1207', 'H1208', 'H1209', 'H1210', 'H1211', 'H1212')
AND NOT EXISTS (SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE AND FACTORY_CODE = '116');

-- 结构3: 11R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE, YEAR, MONTH, BEGIN_DAY, END_DAY, MAX_LH, FACTORY_CODE, IS_DELETE)
SELECT '11R22.5', '11R22.5', CX_MACHINE_CODE, '成型', 2026, 3, 1, 31, 2, '116', '0'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1213', 'H1214', 'H1215', 'H1216', 'H1217', 'H1218')
AND NOT EXISTS (SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE AND FACTORY_CODE = '116');

-- 结构4: 12R22.5 (7台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (STRUCTURE_CODE, STRUCTURE_NAME, CX_MACHINE_CODE, MACHINE_TYPE, YEAR, MONTH, BEGIN_DAY, END_DAY, MAX_LH, FACTORY_CODE, IS_DELETE)
SELECT '12R22.5', '12R22.5', CX_MACHINE_CODE, '成型', 2026, 3, 1, 31, 2, '116', '0'
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1 AND IS_ONLINE = 1
AND CX_MACHINE_CODE IN ('H1219', 'H1220', 'H1221', 'H1222', 'H1223', 'H1224', 'H1225')
AND NOT EXISTS (SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE AND FACTORY_CODE = '116');

-- ---------------------------------------------
-- 2. t_mdm_structure_tread_config - 结构整车配置
-- 配置每个结构的胎面整车条数
-- ---------------------------------------------

-- 清空现有数据（测试用）
-- DELETE FROM t_mdm_structure_tread_config WHERE FACTORY_CODE = '116';

INSERT INTO t_mdm_structure_tread_config (STRUCTURE_CODE, STRUCTURE_NAME, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '215/75R17.5', '215/75R17.5', 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '215/75R17.5' AND FACTORY_CODE = '116');

INSERT INTO t_mdm_structure_tread_config (STRUCTURE_CODE, STRUCTURE_NAME, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '10R22.5', '10R22.5', 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '10R22.5' AND FACTORY_CODE = '116');

INSERT INTO t_mdm_structure_tread_config (STRUCTURE_CODE, STRUCTURE_NAME, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '11R22.5', '11R22.5', 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '11R22.5' AND FACTORY_CODE = '116');

INSERT INTO t_mdm_structure_tread_config (STRUCTURE_CODE, STRUCTURE_NAME, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '12R22.5', '12R22.5', 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '12R22.5' AND FACTORY_CODE = '116');

-- ---------------------------------------------
-- 3. T_CX_STRUCTURE_SHIFT_CAPACITY - 结构班次产能配置
-- 配置每个结构每班次的产能
-- ---------------------------------------------

-- 清空现有数据（测试用）
-- DELETE FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE FACTORY_CODE = '116';

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '215/75R17.5', '215/75R17.5', '成型', 'NIGHT', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '215/75R17.5', '215/75R17.5', '成型', 'DAY', 48, 384, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '215/75R17.5', '215/75R17.5', '成型', 'AFTERNOON', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '215/75R17.5' AND SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116');

-- 10R22.5
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '10R22.5', '10R22.5', '成型', 'NIGHT', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '10R22.5' AND SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '10R22.5', '10R22.5', '成型', 'DAY', 48, 384, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '10R22.5' AND SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '10R22.5', '10R22.5', '成型', 'AFTERNOON', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '10R22.5' AND SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116');

-- 11R22.5
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '11R22.5', '11R22.5', '成型', 'NIGHT', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '11R22.5' AND SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '11R22.5', '11R22.5', '成型', 'DAY', 48, 384, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '11R22.5' AND SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '11R22.5', '11R22.5', '成型', 'AFTERNOON', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '11R22.5' AND SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116');

-- 12R22.5
INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '12R22.5', '12R22.5', '成型', 'NIGHT', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '12R22.5' AND SHIFT_CODE = 'NIGHT' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '12R22.5', '12R22.5', '成型', 'DAY', 48, 384, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '12R22.5' AND SHIFT_CODE = 'DAY' AND FACTORY_CODE = '116');

INSERT INTO T_CX_STRUCTURE_SHIFT_CAPACITY (STRUCTURE_CODE, STRUCTURE_NAME, MACHINE_TYPE, SHIFT_CODE, HOURLY_CAPACITY, DAILY_CAPACITY, TREAD_COUNT, FACTORY_CODE, IS_DELETE)
SELECT '12R22.5', '12R22.5', '成型', 'AFTERNOON', 24, 192, 200, '116', '0' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE STRUCTURE_CODE = '12R22.5' AND SHIFT_CODE = 'AFTERNOON' AND FACTORY_CODE = '116');

-- ---------------------------------------------
-- 4. T_LH_SCHEDULE_RESULT - 硫化排程结果
-- 创建测试用的硫化任务数据
-- ---------------------------------------------

-- 注意：确保 T_LH_SCHEDULE_RESULT 表的 EMBRYO_CODE 和 STRUCTURE_NAME 已填充
-- 以下SQL为测试目的，请根据实际情况调整

-- 验证数据
SELECT 'T_MP_STRUCTURE_ALLOCATION' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM T_MP_STRUCTURE_ALLOCATION WHERE FACTORY_CODE = '116' AND IS_DELETE = '0'
UNION ALL
SELECT 't_mdm_structure_tread_config', COUNT(*) FROM t_mdm_structure_tread_config WHERE FACTORY_CODE = '116' AND IS_DELETE = '0'
UNION ALL
SELECT 'T_CX_STRUCTURE_SHIFT_CAPACITY', COUNT(*) FROM T_CX_STRUCTURE_SHIFT_CAPACITY WHERE FACTORY_CODE = '116' AND IS_DELETE = '0';
