-- ============================================
-- APS成型排程系统测试数据 (MySQL版)
-- 基于MpCxCapacityConfiguration实体类完整字段
-- 继承链: BaseEntity -> ApsBaseEntity -> MpCxCapacityConfiguration
-- ============================================

-- ---------------------------------------------
-- 1. T_MP_STRUCTURE_ALLOCATION - 结构排产配置
-- MpCxCapacityConfiguration 字段:
-- FACTORY_CODE, YEAR, MONTH, MONTH_PLAN_VERSION, PRODUCTION_VERSION,
-- PLAN_TYPE, STRUCTURE_NAME, NET_QTY, LOSS_QTY,
-- CX_MACHINE_CODE, BEGIN_DAY, END_DAY, ALLOT_DAYS,
-- CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, REMARK
-- ---------------------------------------------

-- 结构1: 215/75R17.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    YEAR, MONTH, MONTH_PLAN_VERSION, PRODUCTION_VERSION, PLAN_TYPE,
    STRUCTURE_NAME, NET_QTY, LOSS_QTY,
    CX_MACHINE_CODE, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT 
    2026, 3, '1.0', '1.0', '01',
    '215/75R17.5', 0, 0,
    CX_MACHINE_CODE, 1, 31, 31,
    '116', 'admin', NOW(), 'admin', NOW()
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1
AND CX_MACHINE_CODE IN ('H1201', 'H1202', 'H1203', 'H1204', 'H1205', 'H1206')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_NAME = '215/75R17.5'
);

-- 结构2: 10R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    YEAR, MONTH, MONTH_PLAN_VERSION, PRODUCTION_VERSION, PLAN_TYPE,
    STRUCTURE_NAME, NET_QTY, LOSS_QTY,
    CX_MACHINE_CODE, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT 
    2026, 3, '1.0', '1.0', '01',
    '10R22.5', 0, 0,
    CX_MACHINE_CODE, 1, 31, 31,
    '116', 'admin', NOW(), 'admin', NOW()
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1
AND CX_MACHINE_CODE IN ('H1207', 'H1208', 'H1209', 'H1210', 'H1211', 'H1212')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_NAME = '10R22.5'
);

-- 结构3: 11R22.5 (6台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    YEAR, MONTH, MONTH_PLAN_VERSION, PRODUCTION_VERSION, PLAN_TYPE,
    STRUCTURE_NAME, NET_QTY, LOSS_QTY,
    CX_MACHINE_CODE, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT 
    2026, 3, '1.0', '1.0', '01',
    '11R22.5', 0, 0,
    CX_MACHINE_CODE, 1, 31, 31,
    '116', 'admin', NOW(), 'admin', NOW()
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1
AND CX_MACHINE_CODE IN ('H1213', 'H1214', 'H1215', 'H1216', 'H1217', 'H1218')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_NAME = '11R22.5'
);

-- 结构4: 12R22.5 (7台机台)
INSERT INTO T_MP_STRUCTURE_ALLOCATION (
    YEAR, MONTH, MONTH_PLAN_VERSION, PRODUCTION_VERSION, PLAN_TYPE,
    STRUCTURE_NAME, NET_QTY, LOSS_QTY,
    CX_MACHINE_CODE, BEGIN_DAY, END_DAY, ALLOT_DAYS,
    FACTORY_CODE, CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME
)
SELECT 
    2026, 3, '1.0', '1.0', '01',
    '12R22.5', 0, 0,
    CX_MACHINE_CODE, 1, 31, 31,
    '116', 'admin', NOW(), 'admin', NOW()
FROM T_MDM_MOLDING_MACHINE
WHERE FACTORY_CODE = '116' AND IS_DELETE = '0' AND IS_ACTIVE = 1
AND CX_MACHINE_CODE IN ('H1219', 'H1220', 'H1221', 'H1222', 'H1223', 'H1224', 'H1225')
AND NOT EXISTS (
    SELECT 1 FROM T_MP_STRUCTURE_ALLOCATION 
    WHERE CX_MACHINE_CODE = T_MDM_MOLDING_MACHINE.CX_MACHINE_CODE 
    AND FACTORY_CODE = '116' AND STRUCTURE_NAME = '12R22.5'
);

-- ---------------------------------------------
-- 2. t_mdm_structure_tread_config - 结构整车配置
-- MdmStructureTreadConfig 字段:
-- STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
-- CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, IS_DELETE
-- ---------------------------------------------

INSERT INTO t_mdm_structure_tread_config (
    STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, IS_DELETE
)
SELECT '215/75R17.5', 200, '1.0', 'C001', '116',
    'admin', NOW(), 'admin', NOW(), '0'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '215/75R17.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, IS_DELETE
)
SELECT '10R22.5', 200, '1.0', 'C001', '116',
    'admin', NOW(), 'admin', NOW(), '0'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '10R22.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, IS_DELETE
)
SELECT '11R22.5', 200, '1.0', 'C001', '116',
    'admin', NOW(), 'admin', NOW(), '0'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '11R22.5' AND FACTORY_CODE = '116'
);

INSERT INTO t_mdm_structure_tread_config (
    STRUCTURE_CODE, TREAD_COUNT, DATA_VERSION, COMPANY_CODE, FACTORY_CODE,
    CREATE_BY, CREATE_TIME, UPDATE_BY, UPDATE_TIME, IS_DELETE
)
SELECT '12R22.5', 200, '1.0', 'C001', '116',
    'admin', NOW(), 'admin', NOW(), '0'
FROM DUAL WHERE NOT EXISTS (
    SELECT 1 FROM t_mdm_structure_tread_config WHERE STRUCTURE_CODE = '12R22.5' AND FACTORY_CODE = '116'
);

-- ---------------------------------------------
-- 3. 验证查询
-- ---------------------------------------------
SELECT STRUCTURE_NAME, COUNT(*) AS MACHINE_COUNT
FROM T_MP_STRUCTURE_ALLOCATION
WHERE FACTORY_CODE = '116'
GROUP BY STRUCTURE_NAME
ORDER BY STRUCTURE_NAME;

SELECT STRUCTURE_CODE, TREAD_COUNT 
FROM t_mdm_structure_tread_config 
WHERE FACTORY_CODE = '116'
ORDER BY STRUCTURE_CODE;
